### ISSUE TITLE
Wave not visible with ionic/capacitor/ios

### ISSUE THREAD

**Issue by davidecampello** [wavesurfer-js/wavesurfer.js#2182]
Hello, I'm having an issue using ionic/angular with capacitor app. The wave is rendered correctly when I run the app in web, but It's not visible when I run as capacitor app in ios.
In my configuration i have barWidth: 1, but it's not working..
I tried with iphone 6/ios 12 and with iphone 12 ios 14 (both phone and emulator)

I created a little demo to reproduce the problem.
You can find it here:
[https://github.com/davidecampello/ionic-capacitor-wavesurfer-test](https://github.com/davidecampello/ionic-capacitor-wavesurfer-test)

I think the problem is similar to #2091 

Thanks
Davide

**Comment by thijstriemstra** [comment]
Make sure you create the audiocontext after a user-gesture on iOS, see the microphone example source: https://github.com/katspaugh/wavesurfer.js/blob/master/example/microphone/app.js

**Comment by davidecampello** [comment]
Hi @thijstriemstra, thanks for your answer. I tried but It's still not working. 
I committed the update into the repository if you have time to try.
Thanks

I attach some screenshots if can help

![image](https://user-images.githubusercontent.com/21193922/107246527-9f636d80-6a30-11eb-97c9-39c7d4330d6b.png)
![image](https://user-images.githubusercontent.com/21193922/107246406-82c73580-6a30-11eb-8b88-ec1746e8c334.png)
![image](https://user-images.githubusercontent.com/21193922/107246331-7216bf80-6a30-11eb-8043-104d0c561858.png)

**Comment by entonbiba** [comment]
@davidecampello this issue should be fixed once this pull request gets merged for safari / ios #2176

Try the following code for now:
```
var audioios = document.createElement('audio');
  | audioios.id = 'audio-player-iosfix';
  | audioios.src = 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU2LjM2LjEwMAAAAAAAAAAAAAAA//OEAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAEAAABIADAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1dXV6urq6urq6urq6urq6urq6urq6urq6urq6v////////////////////////////////8AAAAATGF2YzU2LjQxAAAAAAAAAAAAAAAAJAAAAAAAAAAAASDs90hvAAAAAAAAAAAAAAAAAAAA//MUZAAAAAGkAAAAAAAAA0gAAAAATEFN//MUZAMAAAGkAAAAAAAAA0gAAAAARTMu//MUZAYAAAGkAAAAAAAAA0gAAAAAOTku//MUZAkAAAGkAAAAAAAAA0gAAAAANVVV';
  | audioios.type = 'audio/mpeg';
  |  
  | audioios.play();
  | audioios.remove();
```

**Comment by davidecampello** [comment]
Hi @entonbiba, thank you! I'll try and 'll let you know..
Thank you!

**Comment by davidecampello** [comment]
Hi @thijstriemstra, unfortunatly it's not working.
I committed the fix in the repository if someone want to try...

**Comment by davidecampello** [comment]
I noticed something different. It's still not working but I can see a small black vertical line on left.
I attach a screenshot if it can help.
Thanks!

![Screenshot 2021-03-09 at 12 14 48](https://user-images.githubusercontent.com/21193922/110462517-1859f180-80d1-11eb-8f09-29235d5f3725.png)

**Comment by sundayz** [comment]
iOS 14.5 brings huge improvements to Safari WebAudio compatibility, see if that makes a difference.
